// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loan.proto

#include "loan.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace loan {
class MsgLogDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MsgLog> _instance;
} _MsgLog_default_instance_;
}  // namespace loan
static void InitDefaultsscc_info_MsgLog_loan_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::loan::_MsgLog_default_instance_;
    new (ptr) ::loan::MsgLog();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_MsgLog_loan_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_MsgLog_loan_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_loan_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_loan_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_loan_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_loan_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::loan::MsgLog, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::loan::MsgLog, msg_type_),
  PROTOBUF_FIELD_OFFSET(::loan::MsgLog, msg_cmd_),
  PROTOBUF_FIELD_OFFSET(::loan::MsgLog, log_time_seconds_),
  PROTOBUF_FIELD_OFFSET(::loan::MsgLog, log_time_index_),
  PROTOBUF_FIELD_OFFSET(::loan::MsgLog, service_name_),
  PROTOBUF_FIELD_OFFSET(::loan::MsgLog, service_path_),
  PROTOBUF_FIELD_OFFSET(::loan::MsgLog, log_contents_),
  PROTOBUF_FIELD_OFFSET(::loan::MsgLog, log_option_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::loan::MsgLog)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::loan::_MsgLog_default_instance_),
};

const char descriptor_table_protodef_loan_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nloan.proto\022\004loan\"\263\001\n\006MsgLog\022\020\n\010msg_typ"
  "e\030\001 \001(\t\022\017\n\007msg_cmd\030\002 \001(\005\022\030\n\020log_time_sec"
  "onds\030\003 \001(\003\022\026\n\016log_time_index\030\004 \001(\005\022\024\n\014se"
  "rvice_name\030\005 \001(\t\022\024\n\014service_path\030\006 \001(\t\022\024"
  "\n\014log_contents\030\007 \001(\t\022\022\n\nlog_option\030\010 \001(\t"
  "b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_loan_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_loan_2eproto_sccs[1] = {
  &scc_info_MsgLog_loan_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_loan_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_loan_2eproto = {
  false, false, descriptor_table_protodef_loan_2eproto, "loan.proto", 208,
  &descriptor_table_loan_2eproto_once, descriptor_table_loan_2eproto_sccs, descriptor_table_loan_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_loan_2eproto::offsets,
  file_level_metadata_loan_2eproto, 1, file_level_enum_descriptors_loan_2eproto, file_level_service_descriptors_loan_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_loan_2eproto(&descriptor_table_loan_2eproto);
namespace loan {

// ===================================================================

class MsgLog::_Internal {
 public:
};

MsgLog::MsgLog(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:loan.MsgLog)
}
MsgLog::MsgLog(const MsgLog& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  msg_type_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_msg_type().empty()) {
    msg_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_msg_type(), 
      GetArena());
  }
  service_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_service_name().empty()) {
    service_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_service_name(), 
      GetArena());
  }
  service_path_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_service_path().empty()) {
    service_path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_service_path(), 
      GetArena());
  }
  log_contents_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_log_contents().empty()) {
    log_contents_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_log_contents(), 
      GetArena());
  }
  log_option_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_log_option().empty()) {
    log_option_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_log_option(), 
      GetArena());
  }
  ::memcpy(&log_time_seconds_, &from.log_time_seconds_,
    static_cast<size_t>(reinterpret_cast<char*>(&log_time_index_) -
    reinterpret_cast<char*>(&log_time_seconds_)) + sizeof(log_time_index_));
  // @@protoc_insertion_point(copy_constructor:loan.MsgLog)
}

void MsgLog::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_MsgLog_loan_2eproto.base);
  msg_type_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  service_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  service_path_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  log_contents_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  log_option_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&log_time_seconds_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&log_time_index_) -
      reinterpret_cast<char*>(&log_time_seconds_)) + sizeof(log_time_index_));
}

MsgLog::~MsgLog() {
  // @@protoc_insertion_point(destructor:loan.MsgLog)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void MsgLog::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  msg_type_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  service_name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  service_path_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  log_contents_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  log_option_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void MsgLog::ArenaDtor(void* object) {
  MsgLog* _this = reinterpret_cast< MsgLog* >(object);
  (void)_this;
}
void MsgLog::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void MsgLog::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MsgLog& MsgLog::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MsgLog_loan_2eproto.base);
  return *internal_default_instance();
}


void MsgLog::Clear() {
// @@protoc_insertion_point(message_clear_start:loan.MsgLog)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  msg_type_.ClearToEmpty();
  service_name_.ClearToEmpty();
  service_path_.ClearToEmpty();
  log_contents_.ClearToEmpty();
  log_option_.ClearToEmpty();
  ::memset(&log_time_seconds_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&log_time_index_) -
      reinterpret_cast<char*>(&log_time_seconds_)) + sizeof(log_time_index_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MsgLog::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string msg_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_msg_type();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "loan.MsgLog.msg_type"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 msg_cmd = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          msg_cmd_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 log_time_seconds = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          log_time_seconds_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 log_time_index = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          log_time_index_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string service_name = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          auto str = _internal_mutable_service_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "loan.MsgLog.service_name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string service_path = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          auto str = _internal_mutable_service_path();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "loan.MsgLog.service_path"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string log_contents = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          auto str = _internal_mutable_log_contents();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "loan.MsgLog.log_contents"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string log_option = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 66)) {
          auto str = _internal_mutable_log_option();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "loan.MsgLog.log_option"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* MsgLog::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:loan.MsgLog)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string msg_type = 1;
  if (this->msg_type().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_msg_type().data(), static_cast<int>(this->_internal_msg_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "loan.MsgLog.msg_type");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_msg_type(), target);
  }

  // int32 msg_cmd = 2;
  if (this->msg_cmd() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_msg_cmd(), target);
  }

  // int64 log_time_seconds = 3;
  if (this->log_time_seconds() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(3, this->_internal_log_time_seconds(), target);
  }

  // int32 log_time_index = 4;
  if (this->log_time_index() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(4, this->_internal_log_time_index(), target);
  }

  // string service_name = 5;
  if (this->service_name().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_service_name().data(), static_cast<int>(this->_internal_service_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "loan.MsgLog.service_name");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_service_name(), target);
  }

  // string service_path = 6;
  if (this->service_path().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_service_path().data(), static_cast<int>(this->_internal_service_path().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "loan.MsgLog.service_path");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_service_path(), target);
  }

  // string log_contents = 7;
  if (this->log_contents().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_log_contents().data(), static_cast<int>(this->_internal_log_contents().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "loan.MsgLog.log_contents");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_log_contents(), target);
  }

  // string log_option = 8;
  if (this->log_option().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_log_option().data(), static_cast<int>(this->_internal_log_option().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "loan.MsgLog.log_option");
    target = stream->WriteStringMaybeAliased(
        8, this->_internal_log_option(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:loan.MsgLog)
  return target;
}

size_t MsgLog::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:loan.MsgLog)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string msg_type = 1;
  if (this->msg_type().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_msg_type());
  }

  // string service_name = 5;
  if (this->service_name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_service_name());
  }

  // string service_path = 6;
  if (this->service_path().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_service_path());
  }

  // string log_contents = 7;
  if (this->log_contents().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_log_contents());
  }

  // string log_option = 8;
  if (this->log_option().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_log_option());
  }

  // int64 log_time_seconds = 3;
  if (this->log_time_seconds() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_log_time_seconds());
  }

  // int32 msg_cmd = 2;
  if (this->msg_cmd() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_msg_cmd());
  }

  // int32 log_time_index = 4;
  if (this->log_time_index() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_log_time_index());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MsgLog::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:loan.MsgLog)
  GOOGLE_DCHECK_NE(&from, this);
  const MsgLog* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<MsgLog>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:loan.MsgLog)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:loan.MsgLog)
    MergeFrom(*source);
  }
}

void MsgLog::MergeFrom(const MsgLog& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:loan.MsgLog)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.msg_type().size() > 0) {
    _internal_set_msg_type(from._internal_msg_type());
  }
  if (from.service_name().size() > 0) {
    _internal_set_service_name(from._internal_service_name());
  }
  if (from.service_path().size() > 0) {
    _internal_set_service_path(from._internal_service_path());
  }
  if (from.log_contents().size() > 0) {
    _internal_set_log_contents(from._internal_log_contents());
  }
  if (from.log_option().size() > 0) {
    _internal_set_log_option(from._internal_log_option());
  }
  if (from.log_time_seconds() != 0) {
    _internal_set_log_time_seconds(from._internal_log_time_seconds());
  }
  if (from.msg_cmd() != 0) {
    _internal_set_msg_cmd(from._internal_msg_cmd());
  }
  if (from.log_time_index() != 0) {
    _internal_set_log_time_index(from._internal_log_time_index());
  }
}

void MsgLog::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:loan.MsgLog)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgLog::CopyFrom(const MsgLog& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:loan.MsgLog)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgLog::IsInitialized() const {
  return true;
}

void MsgLog::InternalSwap(MsgLog* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  msg_type_.Swap(&other->msg_type_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  service_name_.Swap(&other->service_name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  service_path_.Swap(&other->service_path_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  log_contents_.Swap(&other->log_contents_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  log_option_.Swap(&other->log_option_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MsgLog, log_time_index_)
      + sizeof(MsgLog::log_time_index_)
      - PROTOBUF_FIELD_OFFSET(MsgLog, log_time_seconds_)>(
          reinterpret_cast<char*>(&log_time_seconds_),
          reinterpret_cast<char*>(&other->log_time_seconds_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MsgLog::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace loan
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::loan::MsgLog* Arena::CreateMaybeMessage< ::loan::MsgLog >(Arena* arena) {
  return Arena::CreateMessageInternal< ::loan::MsgLog >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
