# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loan.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='loan.proto',
  package='loan',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nloan.proto\x12\x04loan\"\x99\x01\n\x06MsgLog\x12\'\n\x08msg_type\x18\x01 \x01(\x0e\x32\x15.loan.MsgLog.Msg_Type\x12\x0f\n\x07msg_cmd\x18\x02 \x01(\x05\x12\x14\n\x0cservice_name\x18\x03 \x01(\t\x12\x13\n\x0bLogContents\x18\x04 \x01(\t\"*\n\x08Msg_Type\x12\x0c\n\x08SEND_LOG\x10\x00\x12\x10\n\x0cSEND_COLLECT\x10\x01\x62\x06proto3'
)



_MSGLOG_MSG_TYPE = _descriptor.EnumDescriptor(
  name='Msg_Type',
  full_name='loan.MsgLog.Msg_Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SEND_LOG', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SEND_COLLECT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=132,
  serialized_end=174,
)
_sym_db.RegisterEnumDescriptor(_MSGLOG_MSG_TYPE)


_MSGLOG = _descriptor.Descriptor(
  name='MsgLog',
  full_name='loan.MsgLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_type', full_name='loan.MsgLog.msg_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg_cmd', full_name='loan.MsgLog.msg_cmd', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='service_name', full_name='loan.MsgLog.service_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='LogContents', full_name='loan.MsgLog.LogContents', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MSGLOG_MSG_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=174,
)

_MSGLOG.fields_by_name['msg_type'].enum_type = _MSGLOG_MSG_TYPE
_MSGLOG_MSG_TYPE.containing_type = _MSGLOG
DESCRIPTOR.message_types_by_name['MsgLog'] = _MSGLOG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgLog = _reflection.GeneratedProtocolMessageType('MsgLog', (_message.Message,), {
  'DESCRIPTOR' : _MSGLOG,
  '__module__' : 'loan_pb2'
  # @@protoc_insertion_point(class_scope:loan.MsgLog)
  })
_sym_db.RegisterMessage(MsgLog)


# @@protoc_insertion_point(module_scope)
