version: '3.7'

networks:
  bridge:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  # db => elasticsearch
  ela:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: ela
    privileged: true
    privileged: true
    volumes:
      - /Users/leegiljae/Disk/01_Project/log_analyzer/loan:/share
    ports:
      - 9200:9200/tcp
      - 9300:9300/tcp
    stdin_open: true
    tty: true
    networks:
      bridge:
        ipv4_address: 172.20.0.2
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    command: yum install net-tools
    command: yum install curl

  # 로그 분석기 
  anal_1:
    image: loan_dev
    container_name: anal_1
    privileged: true
    volumes:
      - /Users/leegiljae/Disk/01_Project/log_analyzer/loan:/share
    ports:
      - 4444:4444/tcp
    stdin_open: true
    tty: true
    networks:
      bridge:
        ipv4_address: 172.20.0.3

  # 로그 분석기 
  anal_2:
    image: loan_dev
    container_name: anal_2
    privileged: true
    volumes:
      - /Users/leegiljae/Disk/01_Project/log_analyzer/loan:/share
    ports:
      - 5555:5555/tcp
    stdin_open: true
    tty: true
    networks:
      bridge:
        ipv4_address: 172.20.0.4

  # 중간 버퍼 엔진
  buffer:
    image: loan_dev
    container_name: buffer
    privileged: true
    ports:
      - 3333:3333/tcp
    volumes:
      - /Users/leegiljae/Disk/01_Project/log_analyzer/loan:/share
    stdin_open: true
    tty: true
    networks:
      bridge:
        ipv4_address: 172.20.0.5

  # 로그 수집기
  col_1:
    image: loan_dev
    container_name: col_1
    privileged: true
    volumes:
      - /Users/leegiljae/Disk/01_Project/log_analyzer/loan:/share
    stdin_open: true
    tty: true
    networks:
      bridge:
        ipv4_address: 172.20.0.6

  # 로그 수집기
  col_2:
    image: loan_dev
    container_name: col_2
    privileged: true
    volumes:
      - /Users/leegiljae/Disk/01_Project/log_analyzer/loan:/share
    stdin_open: true
    tty: true
    networks:
      bridge:
        ipv4_address: 172.20.0.7
